# Generated by Django 3.2.7 on 2024-04-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211205_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default='', max_length=35, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(default='', max_length=45, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='full_desk',
            field=models.TextField(default='', max_length=500, verbose_name='Повний опис'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='main/images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(default='', max_length=35, verbose_name='Назва'),
        ),
    ]
