# Generated by Django 3.2.7 on 2024-04-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_parking_parking_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_place',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Номер автостояночного місця'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='type',
            field=models.CharField(choices=[('SM', 'Багатоповерхова парковка'), ('SF', 'Не крита парковка'), ('UG', 'Підземна парковка')], max_length=2, verbose_name='Тип'),
        ),
    ]
