# Generated by Django 3.2.7 on 2024-04-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20240417_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Кількість паркомісць'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='type',
            field=models.CharField(choices=[('SM', 'Багатоповерхова парковка'), ('SF', 'Не крита парковка'), ('UG', 'Підземна парковка')], max_length=2, verbose_name='Тип'),
        ),
    ]
