# Generated by Django 3.2.7 on 2024-04-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_parking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='type',
            field=models.CharField(choices=[('SM', 'Багатоповерхова парковка'), ('SF', 'Не крита парковка'), ('UG', 'Підземна парковка')], max_length=2, verbose_name='Тип'),
        ),
    ]
