# Generated by Django 3.2.7 on 2024-04-18 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20240418_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='type',
            field=models.CharField(choices=[('SF', 'Не крита парковка'), ('UG', 'Підземна парковка'), ('SM', 'Багатоповерхова парковка')], max_length=2, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='parking_place',
            name='parking',
            field=models.ForeignKey(db_column="<class 'main.models.Parking'><django.db.models.fields.IntegerField>", on_delete=django.db.models.deletion.CASCADE, to='main.parking'),
        ),
    ]
