# Generated by Django 3.2.7 on 2024-04-18 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20240418_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість паркомісць'),
        ),
        migrations.AlterField(
            model_name='parking_place',
            name='distance_to_exit',
            field=models.PositiveIntegerField(verbose_name='Відстань до виїзду'),
        ),
        migrations.AlterField(
            model_name='parking_place',
            name='number',
            field=models.IntegerField(default=0, unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Номер автостояночного місця'),
        ),
    ]
