# Generated by Django 3.2.7 on 2024-04-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20240418_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AlterField(
            model_name='parking',
            name='type',
            field=models.CharField(choices=[('SM', 'Багатоповерхова парковка'), ('UG', 'Підземна парковка'), ('SF', 'Не крита парковка')], max_length=2, verbose_name='Тип'),
        ),
    ]
