# Generated by Django 3.2.7 on 2024-04-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20240418_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_place',
            name='status',
            field=models.CharField(choices=[('PR', 'Місце заброньоване'), ('PT', 'Місце зайняте'), ('PF', 'Місце вільне')], default='PF', max_length=2, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='type',
            field=models.CharField(choices=[('SF', 'Не крита парковка'), ('UG', 'Підземна парковка'), ('SM', 'Багатоповерхова парковка')], max_length=2, verbose_name='Тип'),
        ),
    ]
