# Generated by Django 3.2.7 on 2024-04-18 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20240418_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_place',
            name='number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Номер автостояночного місця'),
        ),
        migrations.AlterField(
            model_name='parking_place',
            name='status',
            field=models.CharField(choices=[('PR', 'Місце заброньоване'), ('PT', 'Місце зайняте'), ('PF', 'Місце вільне')], default='PF', max_length=2, verbose_name='Статус'),
        ),
    ]
