# Generated by Django 3.2.7 on 2024-04-20 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0018_auto_20240420_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_place',
            name='reserved_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parking',
            name='type',
            field=models.CharField(choices=[('SM', 'Багатоповерхова парковка'), ('SF', 'Не крита парковка'), ('UG', 'Підземна парковка')], max_length=2, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='parking_place',
            name='status',
            field=models.CharField(choices=[('PF', 'Місце вільне'), ('PR', 'Місце заброньоване'), ('PT', 'Місце зайняте')], default='PF', max_length=2, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
