# Generated by Django 3.2.7 on 2024-04-21 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0019_auto_20240420_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_place',
            name='reserved_qr',
            field=models.ImageField(blank=True, null=True, upload_to='main/parking/qr'),
        ),
        migrations.AlterField(
            model_name='parking_place',
            name='reserved_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Зарезервований'),
        ),
        migrations.AlterField(
            model_name='parking_place',
            name='status',
            field=models.CharField(choices=[('PF', 'Місце вільне'), ('PT', 'Місце зайняте'), ('PR', 'Місце заброньоване')], default='PF', max_length=2, verbose_name='Статус'),
        ),
    ]
