# Generated by Django 4.2.11 on 2024-04-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_parking_place_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='urls',
            field=models.CharField(default='', max_length=100, verbose_name='Посилання на карту'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='type',
            field=models.CharField(choices=[('SM', 'Багатоповерхова парковка'), ('UG', 'Підземна парковка'), ('SF', 'Не крита парковка')], max_length=2, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='parking_place',
            name='status',
            field=models.CharField(choices=[('PT', 'Місце зайняте'), ('PF', 'Місце вільне'), ('PR', 'Місце заброньоване')], default='PF', max_length=2, verbose_name='Статус'),
        ),
    ]
