# Generated by Django 4.2.11 on 2024-04-27 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_parking_urls_alter_parking_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_place',
            name='parking_cost',
            field=models.IntegerField(default=30, verbose_name='Вартість бронювання за годину'),
        ),
        migrations.AddField(
            model_name='parking_place',
            name='parking_time',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Термін паркування'),
        ),
        migrations.AddField(
            model_name='parking_place',
            name='start_time_reserved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='type',
            field=models.CharField(choices=[('UG', 'Підземна парковка'), ('SF', 'Не крита парковка'), ('SM', 'Багатоповерхова парковка')], max_length=2, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='parking_place',
            name='status',
            field=models.CharField(choices=[('PF', 'Місце вільне'), ('PR', 'Місце заброньоване'), ('PT', 'Місце зайняте')], default='PF', max_length=2, verbose_name='Статус'),
        ),
    ]
