# Generated by Django 4.2.11 on 2024-04-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_parking_type_alter_parking_place_parking_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_place',
            name='end_time_reserved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='type',
            field=models.CharField(choices=[('UG', 'Підземна парковка'), ('SM', 'Багатоповерхова парковка'), ('SF', 'Не крита парковка')], max_length=2, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='parking_place',
            name='status',
            field=models.CharField(choices=[('PF', 'Місце вільне'), ('PR', 'Місце заброньоване'), ('PT', 'Місце зайняте')], default='PF', max_length=2, verbose_name='Статус'),
        ),
    ]
