# Generated by Django 4.2.11 on 2024-04-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_parking_place_end_time_reserved_alter_parking_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_place',
            name='status',
            field=models.CharField(choices=[('PR', 'Місце заброньоване'), ('PF', 'Місце вільне'), ('PT', 'Місце зайняте')], default='PF', max_length=2, verbose_name='Статус'),
        ),
    ]
