# Generated by Django 4.2.11 on 2024-04-28 11:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0028_alter_parking_place_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='type',
            field=models.CharField(choices=[('SF', 'Не крита парковка'), ('UG', 'Підземна парковка'), ('SM', 'Багатоповерхова парковка')], max_length=2, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='parking_place',
            name='status',
            field=models.CharField(choices=[('PT', 'Місце зайняте'), ('PF', 'Місце вільне'), ('PR', 'Місце заброньоване')], default='PF', max_length=2, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='HistoricalParking_Place',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Номер автостояночного місця')),
                ('parking_cost', models.IntegerField(default=30, verbose_name='Вартість бронювання за годину')),
                ('parking_time', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='Термін паркування')),
                ('start_time_reserved', models.DateTimeField(blank=True, null=True)),
                ('end_time_reserved', models.DateTimeField(blank=True, null=True)),
                ('is_place_for_disable', models.BooleanField(default=False, verbose_name='Місце для інвалідів')),
                ('is_place_for_electric', models.BooleanField(default=False, verbose_name='Місце з підзарядкою')),
                ('distance_to_exit', models.PositiveIntegerField(verbose_name='Відстань до виїзду')),
                ('status', models.CharField(choices=[('PT', 'Місце зайняте'), ('PF', 'Місце вільне'), ('PR', 'Місце заброньоване')], default='PF', max_length=2, verbose_name='Статус')),
                ('reserved_qr', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parking', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.parking')),
                ('reserved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Зарезервований')),
            ],
            options={
                'verbose_name': 'historical parking_ place',
                'verbose_name_plural': 'historical parking_ places',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
