# Generated by Django 4.2.11 on 2024-04-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_historicalparking_place_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparking_place',
            name='status',
            field=models.CharField(choices=[('PT', 'Місце зайняте'), ('PF', 'Місце вільне'), ('PR', 'Місце заброньоване')], default='PF', max_length=2, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='type',
            field=models.CharField(choices=[('SF', 'Не крита парковка'), ('SM', 'Багатоповерхова парковка'), ('UG', 'Підземна парковка')], max_length=2, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='parking_place',
            name='status',
            field=models.CharField(choices=[('PT', 'Місце зайняте'), ('PF', 'Місце вільне'), ('PR', 'Місце заброньоване')], default='PF', max_length=2, verbose_name='Статус'),
        ),
    ]
